# Generated by Django 4.1.6 on 2023-02-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('last_update', models.IntegerField()),
                ('keyword1', models.CharField(default='', max_length=50)),
                ('keyword1_rating', models.FloatField(default=0)),
                ('keyword1_freq', models.IntegerField(default=0)),
                ('keyword2', models.CharField(default='', max_length=50)),
                ('keyword2_rating', models.FloatField(default=0)),
                ('keyword2_freq', models.IntegerField(default=0)),
                ('keyword3', models.CharField(default='', max_length=50)),
                ('keyword3_rating', models.FloatField(default=0)),
                ('keyword3_freq', models.IntegerField(default=0)),
                ('keyword4', models.CharField(default='', max_length=50)),
                ('keyword4_rating', models.FloatField(default=0)),
                ('keyword4_freq', models.IntegerField(default=0)),
                ('keyword5', models.CharField(default='', max_length=50)),
                ('keyword5_rating', models.FloatField(default=0)),
                ('keyword5_freq', models.IntegerField(default=0)),
            ],
        ),
    ]
